In [19]:
!pip install opencv-python

In [1]:
import cv2

In [2]:
img = cv2.imread('img_1.jpeg')

In [3]:
type(img)

numpy.ndarray

In [4]:
img.shape

(540, 820, 3)

In [5]:
# bgr - blue, green, red
img

array([[[140, 104,  96],
        [137, 101,  93],
        [135,  98,  90],
        ...,
        [171, 167,  79],
        [172, 168,  80],
        [172, 168,  80]],

       [[142, 106,  98],
        [140, 104,  96],
        [137, 100,  92],
        ...,
        [171, 167,  79],
        [172, 168,  80],
        [173, 169,  81]],

       [[145, 109, 101],
        [142, 106,  98],
        [139, 103,  95],
        ...,
        [170, 166,  77],
        [171, 167,  78],
        [172, 168,  79]],

       ...,

       [[ 50,  60,  78],
        [ 52,  62,  80],
        [ 50,  60,  78],
        ...,
        [ 61,  48,  56],
        [ 62,  48,  60],
        [ 60,  48,  60]],

       [[ 52,  59,  79],
        [ 55,  62,  82],
        [ 51,  60,  80],
        ...,
        [ 63,  50,  58],
        [ 63,  49,  61],
        [ 61,  49,  61]],

       [[ 53,  60,  80],
        [ 55,  62,  82],
        [ 51,  60,  80],
        ...,
        [ 64,  51,  59],
        [ 65,  51,  63],
        [ 63,  51,  63]]

In [6]:
cv2.imshow('result', img)
cv2.waitKey(0)

-1

In [11]:
# 0 - default camera
# cv2.VideoCapture(0)

# 1 - external webcam
# cv2.VideoCapture(1)

capture = cv2.VideoCapture('video_1.mp4')
i = 0
while True:
    flag, frame = capture.read()
    if flag:
        i += 1
        frame = cv2.resize(frame, None, None, fx=0.5, fy=0.5)
        cv2.imshow('result', frame)
        cv2.imwrite(f'images/img_{i}.png', frame)
        # 27 - ASCII of escape
        if cv2.waitKey(1) == 27:
            break
    else:
        print("Video/Camera not found...")
        break
        
capture.release()
cv2.destroyAllWindows()

Video/Camera not found...


In [12]:
haar_data = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [13]:
haar_data.detectMultiScale(img)

array([[267,  22, 153, 153]])

In [14]:
img_2 = cv2.imread('img_2.webp')

In [15]:
haar_data.detectMultiScale(img_2)

array([[  48,   29,  155,  155],
       [1368,   40,  181,  181],
       [ 480,   86,  140,  140],
       [1091,   96,  127,  127],
       [ 779,  101,  123,  123]])

In [18]:
faces = haar_data.detectMultiScale(img_2)

while True:
    for x,y,w,h in faces:
        cv2.rectangle(img_2, (x,y), (x+w, y+h), (225,0,0), 4)
    cv2.imshow('result', img_2)
    if cv2.waitKey(1) == 27:
        break
        
capture.release()
cv2.destroyAllWindows()

In [20]:
capture = cv2.VideoCapture('video_1.mp4')
while True:
    flag, frame = capture.read()
    if flag:
        i += 1
        frame = cv2.resize(frame, None, None, fx=0.5, fy=0.5)
        faces = haar_data.detectMultiScale(frame)
        for x,y,w,h in faces:
            cv2.rectangle(frame, (x,y), (x+w, y+h), (225,0,0), 4)
        cv2.imshow('result', frame)
        if cv2.waitKey(1) == 27:
            break
    else:
        print("Video/Camera not found...")
        break
        
capture.release()
cv2.destroyAllWindows()