<a href="https://colab.research.google.com/github/brainmentorspvtltd/MSIT_FDP_DeepLearning/blob/main/SimpleANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x = np.array([[1,0,1,0], [1,0,1,1], [0,1,0,1]])
y = np.array([[1],[1],[0]])

In [3]:
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [8]:
inputNeurons = 4
hiddenNeurons = 3
outputNeurons = 1

In [15]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [16]:
weightsHidden = np.random.uniform(size=(inputNeurons, hiddenNeurons))
biasHidden = np.random.uniform(size=(1, hiddenNeurons))

weightsOutput = np.random.uniform(size=(hiddenNeurons, outputNeurons))
biasOutput = np.random.uniform(size=(1, outputNeurons))

In [17]:
weightsHidden

array([[0.75923546, 0.15056198, 0.52875824],
       [0.75381134, 0.38018359, 0.5959384 ],
       [0.18595813, 0.20645962, 0.83853093],
       [0.59660011, 0.77770993, 0.75384591]])

In [18]:
# Feedforward
fx = x.dot(weightsHidden) + biasHidden
hiddenLayer = sigmoid(fx)

fx1 = hiddenLayer.dot(weightsOutput) + biasOutput
outputLayer = sigmoid(fx1)

In [19]:
outputLayer

array([[0.91960896],
       [0.93272732],
       [0.92938795]])